# Generated by Django 3.2 on 2022-07-12 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20220710_1724'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.UniqueConstraint(fields=('name', 'measurement_unit'), name='\nТакой ингредиент уже есть\n'),
        ),
    ]
