# Generated by Django 3.2 on 2022-07-12 09:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220712_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscribing',
            field=models.ManyToManyField(through='users.Subscribe', to=settings.AUTH_USER_MODEL, verbose_name='Подписчики'),
        ),
    ]
